<template>
	<v-card title="Create Account" width="400" class="text-center pa-4" color="secondary">
		<v-sheet class="mx-auto" width="300" color="secondary">
			<v-form @submit.prevent>
				<v-text-field v-model="username" label="Username" outlined required @input="validateUsername"></v-text-field>
				<v-text-field v-model="email" label="Email" outlined required @input="validateEmail"></v-text-field>
				<v-text-field v-model="password" label="Password" type="password" outlined required @input="validatePassword"></v-text-field>
				<v-text-field v-model="confirmPassword" label="Confirm Password" type="password" outlined required @input="validateConfirmPassword"></v-text-field>
				<v-col cols="12">
					<p>{{ statusText }}</p>
				</v-col>
				<v-btn :disabled="!validateForm" @click="createAccount">Create Account</v-btn>
				<v-btn @click="resetForm">Reset</v-btn>
				<v-divider class="ma-4 border-opacity-50"></v-divider>
				<p>Already Have An Account?</p>
				<v-btn class="mt-2" block @click="openlogin">Log In</v-btn>
			</v-form>
		</v-sheet>
	</v-card>
</template>

<script lang="ts">
import { defineComponent } from "vue";
import { createUser } from "@/api.ts";
import { ResponseCodes } from "@/enums/ResponseCodes.ts";

export default defineComponent({
	name: "CreateAccountCard",
	data() {
		return {
			username: "",
			email: "",
			password: "",
			confirmPassword: "",
			validUsername: false,
			validEmail: false,
			validPassword: false,
			validConfirmPassword: false,
			statusText: "",
		};
	},
	computed: {
		validateForm() {
			return (
				this.validUsername &&
				this.validEmail &&
				this.validPassword &&
				this.validConfirmPassword
			);
		},
	},
	methods: {
		validateUsername() {
			this.validUsername = this.username.length > 0;
		},
		validateEmail() {
			this.validEmail = this.email.includes("@");
		},
		validatePassword() {
			this.validPassword = this.password.length > 6;
		},
		validateConfirmPassword() {
			this.validConfirmPassword = this.password === this.confirmPassword;
		},
		async createAccount() {
			const response = await createUser({
				id: "", // should be generated by the server
				username: this.username,
				email: this.email,
				password: this.password,
				bio: "",
			});

			if (response.status === ResponseCodes.CREATED) {
				console.log("Account created");
				this.statusText = "Account created";
				this.resetForm();
			} else {
				console.error(
					"Failed to create account. \n" +
					"Status was: " +
					response.status +
					"\nData was: " +
					response.data,
				);

				this.statusText = `Failed to create account. Error was "${response.data}". See console for more details.`;
			}
		},
		resetForm() {
			this.username = "";
			this.email = "";
			this.password = "";
			this.confirmPassword = "";
			this.validUsername = false;
			this.validEmail = false;
			this.validPassword = false;
			this.validConfirmPassword = false;
		},
		openlogin() {
			this.$router.push("/login");
		},
	},
});
</script>

<style scoped lang="sass">
</style>
