/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

declare module 'vue' {
  export interface GlobalComponents {
    AppFooter: typeof import('./components/AppFooter.vue')['default']
    CreateNewAccountCard: typeof import('./components/CreateNewAccountCard.vue')['default']
    DashBoard: typeof import('./components/DashBoard.vue')['default']
    HelloWorld: typeof import('./components/HelloWorld.vue')['default']
    LoginCard: typeof import('./components/loginCard.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
  }
}
